website/presets/urls.py
from django.urls import path

from . import views
from .views import AboutView, ChangelogView, PresetListView, PresetDetailView, PresetCreateView

app_name = 'presets'
urlpatterns = [
    path('', PresetListView.as_view(), name='index'),
    path('<int:id>/', PresetDetailView.as_view(), name='detail'),
    path('create/', PresetCreateView.as_view(), name='create'),
    path('delete/<int:preset_id>', views.delete, name='delete'),
    path('like/<int:preset_id>', views.like, name='like'),
    path('remove_like/<int:preset_id>', views.remove_like, name='dislike'),
    path('download/<int:preset_id>', views.download, name='download'),
    path('account/<int:user_id>', views.account, name='account'),
    path('update/<int:preset_id>/', views.update, name='update'),
    path('generate', views.generate_presets, name='generate'),
    path('delete-all', views.delete_presets, name='delete-all'),
    path('about', AboutView.as_view(), name='about'),
    path('changelog', ChangelogView.as_view(), name='changelog'),
]

website/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('login', views.login_user, name='login'),
    path('create', views.create_user, name='create'),
    path('logout', views.logout_user, name='logout'),
    path('edit', views.edit_user, name='edit'),
    path('delete', views.delete_user, name='delete')
]

website/website/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path("users/", include("django.contrib.auth.urls")),
    path("users/", include("users.urls")),
    path("", include("presets.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/presets/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from .validators.validators import valid_preset_size, valid_image_size, valid_zip

class PresetImage(models.Model):
    image = models.ImageField(
        upload_to='images',
        validators=[valid_image_size]
    )


class Preset(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=820)
    zip_file = models.FileField(
        upload_to='zip_files',
        validators=[valid_preset_size, valid_zip],
        default='zip_files/default.zip'
    )
    thumbnail_file = models.ImageField(
        upload_to='images',
        validators=[valid_image_size],
        default='images/default.jpg'
    )
    created_at = models.DateTimeField(
        db_index=True, 
        default=timezone.now
    )
    updated_at = models.DateTimeField(auto_now=True)
    
    # User who submitted the preset
    user_who_submitted = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

    # Other thumbnails
    additional_thumbnail_files = models.ManyToManyField(PresetImage)

    # Counts for stats purposes
    like_count = models.IntegerField(default=0)
    download_count = models.IntegerField(default=0)
    view_count = models.IntegerField(default=0)

    # Enum for preset's character type
    class Character(models.TextChoices):
        ALL = 'ALL'
        AOI = 'AOI'
        BOL = 'BOL'
        BORCO = 'BORCO'
        CHAKKAR = 'CHAKKAR'
        CORMAN = 'CORMAN'
        EMMA = 'EMMA'
        ILJAH = 'ILJAH'
        INDRA = 'INDRA'
        JADEEN = 'JADEEN'
        JENNY = 'JENNY'
        KIM = 'KIM'
        KRAL = 'KRAL'
        LALA = 'LALA'
        LEAH = 'LEAH'
        LEE = 'LEE'
        LYNDON = 'LYNDON'
        MAX = 'MAX'
        MAYA = 'MAYA'
        MERCER = 'MERCER'
        MILANNA = 'MILANNA'
        MINOTAUR = 'MINOTAUR'
        MORRIS = 'MORRIS'
        NERO_NERO = 'NERO_NERO'
        RAWN = 'RAWN'
        SERENIA = 'SERENIA'
        SHANNON = 'SHANNON'
        SHEY = 'SHEY'
        SHEYFUTA = 'SHEYFUTA'
        SHIVA = 'SHIVA'
        SONIA = 'SONIA'
        TANYA = 'TANYA'
        TRIBALMALEA1 = 'TRIBALMALEA1'
        ZIAD = 'ZIAD'
        OTHER = 'OTHER'

    character = models.CharField(
        max_length=12,
        choices=Character.choices,
        default=Character.ALL,
    )

    # Additional tables to link users to presets
    likes = models.ManyToManyField(User, related_name="preset_likes")

    def __str__(self):
        return self.name

website/presets/forms.py
from django import forms

from .models import Preset

from .validators.validators import valid_image_size


class PresetForm(forms.ModelForm):
    additional_thumbnail_files = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
        required=False,
        validators=[valid_image_size],
        help_text="Maximum 5MB per image",
        label="Addtional images for the preset"
    )

    def __init__(self, *args, **kwargs):
        super(PresetForm, self).__init__(*args, **kwargs)
        self.fields['zip_file'].widget.attrs.update({
            'accept': 'application/zip'
        })
        self.fields['character'].choices = self.fields['character'].choices[1:]

    class Meta:
        model = Preset
        fields = [
            'name',
            'description',
            'character',
            'zip_file',
            'thumbnail_file',
            'additional_thumbnail_files'
        ]
        labels = {
            'name': "Name of preset",
            'description': "Description of preset",
            'zip_file': "Zip file with the preset contents",
            'thumbnail_file': "Main image for the preset",
        }
        widgets = {
            'description': forms.Textarea,
        }
        help_texts = {
            'name': "Maximum 30 characters",
            'description': "Maximum 820 characters",
            'zip_file': "Maximum 1MB",
            'thumbnail_file': "Maximum 5MB",
        }


class FilterForm(forms.ModelForm):
    sort_choices = (
        ('Newest', 'Newest'),
        ('Oldest', 'Oldest'),
        ('Likes', 'Most Liked'),
        ('Downloads', 'Most Downloaded'),
        ('Views', 'Most Viewed')
    )
    sort_by = forms.ChoiceField(choices=sort_choices)
    
    class Meta:
        model = Preset
        fields = ['character']
        labels = {
            'character': "Character to filter by"
        }

website/presets/views.py
from typing import Any, Dict, Sequence
from django.forms import BaseModelForm
from django.http import FileResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.core.exceptions import ValidationError
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormMixin
from django.db.models import QuerySet


from .models import Preset, PresetImage
from .forms import PresetForm, FilterForm
from .validators.validators import valid_image_size


class PresetListView(FormMixin, ListView):
    model = Preset
    paginate_by = 15
    form_class = FilterForm

    def get_ordering(self) -> Sequence[str]:
        SORTING_FILTER = self.request.GET.get("sort_by")
        
        if SORTING_FILTER:
            if SORTING_FILTER == "Newest":
                return "-created_at"
            elif SORTING_FILTER == 'Oldest':
                return "created_at"
            elif SORTING_FILTER == 'Likes':
                return "-like_count"
            elif SORTING_FILTER == 'Downloads':
                return "-download_count"
            elif SORTING_FILTER == 'Views':
                return "-view_count"
            
            return "-created_at"
        else:
            return "-created_at"

    def get_queryset(self) -> QuerySet[Any]:
        CHARACTER_FILTER = self.request.GET.get('character')

        queryset = super().get_queryset()
        if CHARACTER_FILTER:
            return queryset.filter(character=CHARACTER_FILTER)
        else:
            return queryset


class PresetDetailView(DetailView):
    model = Preset
    pk_url_kwarg = "id"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)

        preset = context['preset']

        context['additional_thumbnails'] = preset.additional_thumbnail_files.all()

        if preset.user_who_submitted.id == self.request.user.id:
            context['is_owner'] = True
        
        return context


class PresetCreateView(CreateView):
    model = Preset
    template_name = "presets/preset_create_form.html"
    form_class = PresetForm
    success_url = "/"
    
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        preset = form.save(commit=False)

        preset.user_who_submitted = self.request.user
        preset.save()

        preset.likes.add(self.request.user)
        preset.like_count += 1

        additional_thumbnail_files = self.request.FILES.getlist('additional_thumbnail_files')
        for thumbnail_file in additional_thumbnail_files:
            preset_image = PresetImage.objects.create(image=thumbnail_file)
            preset.additional_thumbnail_files.add(preset_image)
            preset.save()
        
        messages.success(self.request, message='Preset was successfully created!')
        return redirect("presets:index")


@login_required
def delete(request, preset_id):
    if request.POST:
        Preset.objects.select_for_update().filter(id=preset_id).delete()
        messages.success(request, "Preset successfully deleted!")
        return redirect("presets:index")
    else:
        messages.error(request, 'Error occurred trying to delete preset!')
        return redirect("presets:detail", preset_id=preset_id)


@login_required
def like(request, preset_id):
    if request.POST:
        # Get the actual preset and user objects
        preset = Preset.objects.get(id=preset_id)
        user = User.objects.get(id=request.user.id)

        # Add user to the preset's 'likes' table
        preset.likes.add(user)

        # Increment preset's like count
        preset.like_count += 1
        preset.save()

        success_message = "Preset liked! View liked presets on your account page!"
        messages.success(request, success_message)
        return redirect("presets:detail", id=preset_id)
    else:
        messages.error(request, "Error occurred trying to like preset!")
        return redirect("presets:index")


@login_required
def remove_like(request, preset_id):
    if request.POST:
        # Get the actual preset and user objects
        preset = Preset.objects.get(id=preset_id)
        user = User.objects.get(id=request.user.id)

        # Remove user to the preset's 'likes' table
        preset.likes.remove(user)

        # Decrement preset's like count
        preset.like_count -= 1
        preset.save()

        messages.success(request, "Like removed from preset!")
        return redirect("presets:detail", id=preset_id)
    else:
        messages.error(request, "Error occurred trying to like preset!")
        return redirect("presets:index")


@login_required
def download(request, preset_id):
    if request.POST:
        # Get the preset
        preset = Preset.objects.get(id=preset_id)

        # Increment preset's save counter
        preset.download_count += 1

        preset.save()

        # Open the preset's zip file, read as binary
        return FileResponse(open(preset.zip_file.path, "rb"))
    else:
        messages.error(request, "Error occurred trying to download preset!")
        return redirect("presets:index")


@login_required
def account(request, user_id):
    PRESETS_PER_PAGE = 12

    user = User.objects.get(id=user_id)
    liked_presets = Preset.objects.filter(likes__exact=user_id)

    total_likes, total_downloads, total_views = 0, 0, 0

    for preset in liked_presets:
        if preset.user_who_submitted == user:
            total_likes += preset.like_count
            total_downloads += preset.download_count
            total_views += preset.view_count

    paginator = Paginator(liked_presets, PRESETS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'liked_presets': liked_presets,
        'page_obj': page_obj,
        'curr_user': user,
        'total_likes': total_likes,
        'total_downloads': total_downloads,
        'total_views': total_views
    }

    if user_id == request.user.id:
        context['is_owner'] = True

    return render(request, 'presets/account.html', context)


@login_required
def update(request, preset_id):
    """
    View for updating a preset.

    If a POST is sent, it will try to update the preset with the given data.

    Params:
        preset_id -> ID of preset to be updated
    """
    context = {}
    preset_to_update = get_object_or_404(Preset, pk=preset_id)

    # Checks if the user owns the preset and redirects if not
    if preset_to_update.user_who_submitted.id != request.user.id:
        messages.error(request, 'This preset cannot be updated by the current user.')
        return redirect("presets:detail", id=preset_id)

    form = PresetForm(
        request.POST or None,
        request.FILES or None,
        instance=preset_to_update
    )
    
    if request.POST:
        if form.is_valid():
            preset = form.save(commit=False)

            new_thumbnail_files = request.FILES.getlist('additional_thumbnail_files')

            # Get current thumbnail files, delete them, and then add the new ones
            # Current thumbnails
            if new_thumbnail_files != []:
                # Validate each thumbnail because ModelForm won't do it
                try:
                    for thumbnail_file in new_thumbnail_files:
                        valid_image_size(thumbnail_file)
                except ValidationError as e:
                    context['form'] = form
                    context['preset'] = preset_to_update
                    messages.error(request, e.message)
                    return render(request, 'presets/update.html', context)

                current_thumbnail_files = preset.additional_thumbnail_files.all()

                for thumbnail_file in current_thumbnail_files:
                    thumbnail_file.delete()

            # New thumbnails
            for thumbnail_file in new_thumbnail_files:
                preset_image = PresetImage.objects.create(image=thumbnail_file)
                preset.additional_thumbnail_files.add(preset_image)

            preset.save()
            
            messages.success(request, 'Preset was successfully updated!')
            return redirect("presets:detail", id=preset_id)
        else:
            context['form'] = form
            context['preset'] = preset_to_update
            messages.error(request, 'Preset was not updated!')
            return render(request, 'presets/update.html', context)
    else:
        context['form'] = form
        context['preset'] = preset_to_update
        return render(request, 'presets/update.html', context)


@staff_member_required
def generate_presets(request):
    """
    Generates 100 random test presets.
    """
    number = 1
    while number <= 100:
        Preset.objects.create(
            name="Test Preset #{}".format(number),
            description="Test preset #{}'s description".format(number),
            user_who_submitted=request.user
        )

        number += 1
    
    return redirect("presets:index")


@staff_member_required
def delete_presets(_):
    """
    Deletes all current presets.
    """
    Preset.objects.all().delete()
    return redirect("presets:index")


class AboutView(TemplateView):
    template_name = "presets/about.html"


class ChangelogView(TemplateView):
    template_name = "presets/changelog.html"

website/presets/templates/presets/base.html
<!DOCTYPE html>
<html lang="en-US">
{# Load Bootstrap v5 #}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block header %}{% endblock %}

<body>
    {% include "presets/header-nav.html" %}
    {% block main %}{% endblock %}
    {% block footer %}
    <footer>
        <div class="message">
            {% bootstrap_messages %}
        </div>
        
    </footer>
    {% endblock %}
</body>

</html>

website/presets/templates/presets/header-nav.html
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-xl">
            <a class="navbar-brand link-light" href="{% url 'presets:index' %}">W.L. Presets</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="white" class="bi bi-list" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
                    </svg>
                </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link link-light" href="{% url 'presets:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link-light" href="{% url 'presets:changelog' %}">Changelog</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link link-light" href="{% url 'presets:create' %}">Upload</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link link-light dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'presets:account' user.id %}">Account</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link link-light" href="{% url 'users:login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

website/presets/templates/presets/preset_create_form.html
{% extends 'presets/base.html' %}

{% load bootstrap5 %}

{% block header %}
{% include "presets/header.html" with title="W.L. Presets - Create" %}
{% endblock %}

{% block main %}
<main class="d-flex container-xl mt-5 flex-column flex-xl-row align-items-center">
    <div class="form-container container-fluid col-md-6 col-xl-6 p-4">
        <h2>Upload New Preset</h2>
        <form class="d-flex flex-column mt-5" action="{% url 'presets:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <input class="col-xl-3 mt-3 btn btn-primary" type="submit" value="Submit preset">
            {% endbuttons %}
        </form>
    </div>
</main>
{% endblock %}

website/presets/templates/presets/preset_detail.html
{% extends 'presets/base.html' %}

{% load preset_relations %}

{% block header %}
{% include "presets/header.html" with title="W.L. Presets - Detail" %}
{% endblock %}

{% block main %}
<main class="container-xl mt-5">
    <article class="d-flex flex-xl-row flex-column align-items-center align-items-xl-stretch">
        <div id="carousel-block" class="carousel slide container-fluid detail-img col-md-6 rounded align-self-center img-fluid me-xl-2 mb-xl-0 mb-2" style="height: 22rem">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{{ MEDIA_URL }}{{ preset.thumbnail_file.name }}" class="d-block w-100" style="height: 22rem; object-fit: contain;">
              </div>
              {% if additional_thumbnails %}
              {% for thumbnail in additional_thumbnails %}
              <div class="carousel-item">
                <img src="{{ MEDIA_URL }}{{ thumbnail.image.name }}" class="d-block w-100" style="height: 22rem; object-fit: contain;">
              </div>
              {% endfor %}
              {% endif %}
            </div>
            {% if additional_thumbnails %}
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel-block" data-bs-slide="prev">
              <span aria-hidden="true">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-circle-fill" viewBox="0 0 16 16">
                    <circle cx="8" cy="8" r="8"/>
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="black" class="bi bi-arrow-left-short" viewBox="0 0 32 32">
                        <path d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
                    </svg>
                </svg>
              </span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel-block" data-bs-slide="next">
              <span aria-hidden="true">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-circle-fill" viewBox="0 0 16 16">
                    <circle cx="8" cy="8" r="8"/>
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="black" class="bi bi-arrow-right-short" viewBox="0 0 32 32">
                        <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"/>
                    </svg>
                </svg>
              </span>
              <span class="visually-hidden">Next</span>
            </button>
            {% endif %}
          </div>
        <div class="col-md-6 container-fluid d-flex flex-column py-2 rounded" style="height: 22rem">
            <h2 class="text-break">{{ preset.name }}</h2>
            <h7 class="fs-6 fw-lighter">
                <a class="text-info" href="{% url 'presets:account' preset.user_who_submitted.id %}">{{ preset.user_who_submitted.username }}</a>
                | {{ preset.created_at.date }}
            </h7>
            <p class="text-break">{{ preset.description }}</p>
            <div class="container-fluid d-flex mt-auto justify-content-center px-0">
                {% if user.is_authenticated %}
        
                <!-- Preset's Like function -->
                {% if preset|check_if_preset_liked:request.user %}
                <form class="me-md-auto mx-1" action="{% url 'presets:dislike' preset.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
                            <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z"/>
                        </svg>
                        Remove like
                    </button>
                </form>
                {% else %}
                <form class="me-md-auto mx-1" action="{% url 'presets:like' preset.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-success" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-check2" viewBox="0 0 16 16">
                            <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
                        </svg>
                        Like
                    </button>
                </form>
                {% endif %}
        
                {% if is_owner %}
                <!-- Preset's Edit function -->
                <a class="btn btn-warning" href="{% url 'presets:update' preset.id %}">Edit</a>
                <!-- Preset's Delete function -->
                <form class="mx-md-2" action="{% url 'presets:delete' preset.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
                            <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z"/>
                        </svg>
                        Delete
                    </button>
                </form>
                {% endif %}
        
                <!-- Preset's Download function -->
                <form class="mx-1" action="{% url 'presets:download' preset.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-primary"type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                            <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                            <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                        </svg>
                        Download
                    </button>
                </form>
                {% else %}
                <a class="btn btn-success me-auto" href="{% url 'users:login' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-check2" viewBox="0 0 16 16">
                        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
                    </svg>
                    Like
                </a>
                <a class="btn btn-primary" href="{% url 'users:login' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                        <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                        <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                    </svg>
                    Download
                </a>
                {% endif %}
            </div>
        </div>
    </article>
</main>
{% endblock %}

website/presets/templates/presets/saved.html
{% extends 'presets/base.html' %}

{% block header %}
{% include "presets/header.html" with title="W.L. Presets - Saved" %}
{% endblock %}

{% block main %}
<main>
    <h2>Saved</h2>
    <section>
    {% if saved_presets %}
        {% for preset in saved_presets %}
        <div>
            <a href="{% url 'presets:detail' preset.id %}">
                <img src="{{ MEDIA_URL }}{{ preset.image_file.name }}">
                <p>{{ preset.name }}</p>
            </a>
            <form action="{% url 'presets:unsave' preset.id %}" method="post">
                {% csrf_token %}
                <input id="submit" type="submit" value="Unsave">
            </form>
            <form action="{% url 'presets:download' preset.id %}" method="post">
                {% csrf_token %}
                <input id="submit" type="submit" value="Download">
            </form>
        </div>
        {% endfor %}
    {% else %}
    <p>No presets saved at this time.</p>
    {% endif %}
    </section>
</main>
{% endblock %}