website/presets/urls.py
from django.urls import path

from . import views
from .views import AboutView, ChangelogView, PresetListView, PresetDetailView, PresetCreateView

app_name = 'presets'
urlpatterns = [
    path('', PresetListView.as_view(), name='index'),
    path('<int:id>/', PresetDetailView.as_view(), name='detail'),
    path('create/', PresetCreateView.as_view(), name='create'),
    path('delete/<int:preset_id>', views.delete, name='delete'),
    path('like/<int:preset_id>', views.like, name='like'),
    path('remove_like/<int:preset_id>', views.remove_like, name='dislike'),
    path('download/<int:preset_id>', views.download, name='download'),
    path('account/<int:user_id>', views.account, name='account'),
    path('update/<int:preset_id>/', views.update, name='update'),
    path('generate', views.generate_presets, name='generate'),
    path('delete-all', views.delete_presets, name='delete-all'),
    path('about', AboutView.as_view(), name='about'),
    path('changelog', ChangelogView.as_view(), name='changelog'),
]

website/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('login', views.login_user, name='login'),
    path('create', views.create_user, name='create'),
    path('logout', views.logout_user, name='logout'),
    path('edit', views.edit_user, name='edit'),
    path('delete', views.delete_user, name='delete')
]

website/website/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path("users/", include("django.contrib.auth.urls")),
    path("users/", include("users.urls")),
    path("", include("presets.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/users/models.py
from django.db import models

# Create your models here.

website/users/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, label="Username")
    password = forms.CharField(max_length=50, label="Password", widget=forms.PasswordInput)


class EditUserForm(forms.Form):
    password = forms.CharField(max_length=50, label="Old Password", widget=forms.PasswordInput)
    new_password = forms.CharField(max_length=50, label="New Password", widget=forms.PasswordInput)
    new_password_reentered = forms.CharField(max_length=50, label="New Password Again", widget=forms.PasswordInput)

website/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password
from django.db.utils import IntegrityError
from django.contrib import messages

from .forms import LoginForm, EditUserForm


def login_user(request):
    context = {}
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                request,
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password']
            )

            if user is not None:
                login(request, user)
                messages.success(request, "You are now logged in!")
                return HttpResponseRedirect('/')

            # User doesn't exist; return to login page with error
            context['form'] = LoginForm()
            messages.error(request, "The username/password either don't match or exist.")
            return render(request, 'users/login.html', context)
    else:
        form = LoginForm()
        context['form'] = form
        return render(request, 'users/login.html', context)


def create_user(request):
    context = {}
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            try:
                # Create new user
                # Throws IntegrityError if the username is taken
                user = User.objects.create_user(
                    username=form.cleaned_data['username'],
                    password=form.cleaned_data['password']
                )

                if user is not None:
                    # Save to database, then login the user
                    user.save()
                    login(request, user)
                    messages.success(request, "Welcome " + user.get_username() + "!")
                    return redirect("presets:index")

                context['form'] = LoginForm()
                messages.error(request, 'Creating the account was unsuccessful.')
                return render(request, 'users/login.html', context)
            except IntegrityError:
                context['form'] = form
                messages.error(request, 'Username taken. Please choose a different username.')
                return render(request, 'users/login.html', context)
    else:
        form = LoginForm()
        context['form'] = form
        return render(request, 'users/login.html', context)


@login_required
def logout_user(request):
    logout(request)
    messages.success(request, "You are now logged out!")
    return HttpResponseRedirect('/')    


@login_required
def edit_user(request):
    context = {}
    if request.POST:
        form = EditUserForm(request.POST)
        if form.is_valid():
            try:
                current_password = form.cleaned_data['password']
                
                # If old password is not correct, raise IntegrityError
                if not check_password(current_password, request.user.password):
                    raise IntegrityError

                # Get current user from the database
                current_user = User.objects.get(pk=request.user.id)
                if current_user:
                    current_user.set_password(form.cleaned_data['new_password'])
                    current_user.save()

                    messages.success(request, 'Password change successful!')
                    return redirect('presets:account', user_id=request.user.id)

                context['form'] = EditUserForm()
                messages.error(request, 'Changing password was unsuccessful.')
                return render(request, 'users/edit.html', context)
            except IntegrityError:
                context['form'] = form
                messages.error(request, f'Old password incorrect. Password has not changed.')
                return render(request, 'users/edit.html', context)
    else:
        form = EditUserForm()
        context['form'] = form
        return render(request, 'users/edit.html', context)


@login_required
def delete_user(request):
    if request.POST:
        try:
            user_from_db = User.objects.get(pk=request.user.id)
            user_from_db.delete()
            messages.success(request, "Your account has been successfully deleted.")
            return redirect("presets:index")
        except User.DoesNotExist:
            messages.error(request, "The user does not exist and therefore, cannot be deleted.")
            return redirect("presets:index")
        except:
            messages.error(request, "There was an error trying to delete your account.")
            return redirect("presets:index")
    else:
        return render(request, 'users/delete.html')

website/users/templates/users/delete.html
{% extends 'presets/base.html' %}

{% load bootstrap5 %}

{% block header %}
{% include "presets/header.html" with title="W.L. Presets - Delete" %}
{% endblock %}

{% block main %}
<main class="d-flex container-xl mt-5 flex-column flex-xl-row align-items-center">
    <div class="form-container container-fluid col-md-6 col-xl-6 p-4">
        <h2>Are you sure you want to delete?</h2>
        <form class="d-flex flex-column mt-5" action="{% url 'users:delete' %}" method="post">
            {% csrf_token %}
            {% buttons %}
            <div class="d-flex justify-content-between">
                <a href="{% url 'presets:account' user.id %}" class="col-xl-4 mt-3 btn btn-primary">No, don't delete</a>
                <input class="col-xl-4 mt-3 btn btn-danger" type="submit" value="Yes, delete account">
            </div>            
            {% endbuttons %}
        </form>
    </div>
</main>
{% endblock %}

website/users/templates/users/edit.html
{% extends 'presets/base.html' %}

{% load bootstrap5 %}

{% block header %}
{% include "presets/header.html" with title="W.L. Presets - Create" %}
{% endblock %}

{% block main %}
<main class="d-flex container-xl mt-5 flex-column flex-xl-row align-items-center">
    <div class="form-container container-fluid col-md-6 col-xl-6 p-4">
        <h2>Change Password</h2>
        <form class="d-flex flex-column mt-5" action="{% url 'users:edit' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <input class="col-xl-4 mt-3 btn btn-primary" type="submit" value="Change password">
            {% endbuttons %}
        </form>
    </div>
</main>
{% endblock %}

website/users/templates/users/login.html
{% extends 'presets/base.html' %}

{% load bootstrap5 %}

{% block header %}
{% include 'presets/header.html' with title="W.L. Presets - Login" %}
{% endblock %}

{% block main %}
<main class="d-flex container-xl mt-5 flex-column flex-xl-row align-items-center">
    <div class="form-container col-6 p-4 me-xl-2 mb-xl-0 mb-2">
        <h2>Login</h2>
        <form class="d-flex flex-column mt-5" id="login_user" action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <input class="col-xl-2 mt-3 btn btn-warning" type="submit" value="Login">
            {% endbuttons %}
        </form>
    </div>
    <div class="form-container col-6 p-4 ms-xl-2 mb-xl-0 mb-2">
        <h2>Create New Account</h2>
        <form class="d-flex flex-column mt-5" id="new_user" action="{% url 'users:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <input class="col-xl-2 mt-3 btn btn-warning" type="submit" value="Create">
            {% endbuttons %}
        </form>
    </div>
    
</main>
{% endblock %}